import Head from "next/head";
import HomeSection from "../../section/HomeSection";
import AboutSection from "../../section/AboutSection";
import FlightOptionSection from "../../section/FlightOptionSection";
import AddOnSection from "../../section/AddOnSection";
import FaqSection from "../../section/FaqSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSection />
      <AboutSection />
      <FlightOptionSection />
      <AddOnSection />
      <FaqSection />
    </>
  );
}
